[2023-06-24 14:05:05,320] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_transform scheduled__2020-08-01T00:00:00+00:00 [queued]>
[2023-06-24 14:05:05,328] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_transform scheduled__2020-08-01T00:00:00+00:00 [queued]>
[2023-06-24 14:05:05,328] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-24 14:05:05,330] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-24 14:05:05,330] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-24 14:05:05,343] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): daily_transform> on 2020-08-01 00:00:00+00:00
[2023-06-24 14:05:05,349] {standard_task_runner.py:52} INFO - Started process 678 to run task
[2023-06-24 14:05:05,353] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '2_daily_transformation_analysis', 'daily_transform', 'scheduled__2020-08-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/transform_and_analysis.py', '--cfg-path', '/tmp/tmpjk1_kdfq', '--error-file', '/tmp/tmp9ki6zcq7']
[2023-06-24 14:05:05,353] {standard_task_runner.py:80} INFO - Job 6: Subtask daily_transform
[2023-06-24 14:05:05,402] {task_command.py:369} INFO - Running <TaskInstance: 2_daily_transformation_analysis.daily_transform scheduled__2020-08-01T00:00:00+00:00 [running]> on host 8b5fcfa38f31
[2023-06-24 14:05:05,482] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=2_daily_transformation_analysis
AIRFLOW_CTX_TASK_ID=daily_transform
AIRFLOW_CTX_EXECUTION_DATE=2020-08-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-08-01T00:00:00+00:00
[2023-06-24 14:05:05,483] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-24 14:05:05,485] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt run --models transform --profiles-dir .']
[2023-06-24 14:05:05,494] {subprocess.py:85} INFO - Output:
[2023-06-24 14:05:05,496] {subprocess.py:92} INFO - bash: line 1: dbt: command not found
[2023-06-24 14:05:05,497] {subprocess.py:96} INFO - Command exited with return code 127
[2023-06-24 14:05:05,510] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-24 14:05:05,513] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=2_daily_transformation_analysis, task_id=daily_transform, execution_date=20200801T000000, start_date=20230624T140505, end_date=20230624T140505
[2023-06-24 14:05:05,523] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task daily_transform (Bash command failed. The command returned a non-zero exit code 127.; 678)
[2023-06-24 14:05:05,567] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-24 14:05:05,617] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
